### ISSUE TITLE
login not possible ("cannot unmarshal number into Go value of type string")

### ISSUE THREAD

**Issue by steadfasterX** [mautrix/meta#34] opened 2024-03-08 11:32 UTC
Having issues to login for the first time. Tried with the cURL method and as JSON object following the [guide](https://docs.mau.fi/bridges/go/meta/authentication.html).

Version: [mautrix-meta](https://github.com/mautrix/meta) v0.1.0+dev.[c4157b6a](https://github.com/mautrix/meta/commit/c4157b6a053e39afe842a2db0d071f7415ab9a52) (Mar 7 2024, 13:37:02)

When pasting as cURL:

> Failed to log in: failed to load inbox: messagix-moduleparser: failed to handle hastesupportdata module (failed to unmarshal ssjs data into bbox container: json: cannot unmarshal number into Go value of type messagix.BBoxContainer)

When pasting as json:

~~~
{ "datr":"redacted", "c_user":"redacted", "sb":"redacted", "xs":"redacted" }

or with c_user not quoted:

{ "datr":"redacted", "c_user":redacted, "sb":"redacted", "xs":"redacted" }

or with xs URL "decoded" (checkbox enabled)

all result in:

Failed to parse input as JSON: json: cannot unmarshal number into Go value of type string
~~~

**Comment by jtagcat** [comment] 2024-03-11 22:40
Cannot reproduce. Copied from FF, logged in with yesterday's :latest.

**Comment by steadfasterX** [comment] 2024-03-12 09:35
retried with firefox: same. 
before I have used chromium (brave).

I am using the latest compiled one bc when trying to build I get errors about missing deps:

~~~
# ./build.sh

backfill.go:20:2: package cmp is not in GOROOT (/usr/lib/go-1.19/src/cmp)
/root/go/pkg/mod/maunium.net/go/mautrix@v0.18.0-beta.1.0.20240311183606-94246ffc85aa/crypto/backup/encryptedsessiondata.go:11:2: package crypto/ecdh is not in GOROOT (/usr/lib/go-1.19/src/crypto/ecdh)
messagix/table/wrappedmessage.go:4:2: package slices is not in GOROOT (/usr/lib/go-1.19/src/slices)

# go version
go version go1.19.8 linux/amd64
~~~

**Comment by tulir** [comment] 2024-03-12 10:46
Looks like a duplicate of #28 (you need to get cookies from the correct website matching your configured bridge mode, and you need to be able to use that website for the bridge to work)

**Closed by tulir** 2024-03-12 10:46 UTC
Labels: bug

**Comment by steadfasterX** [comment] 2024-03-12 11:08
> Looks like a duplicate of https://github.com/mautrix/meta/issues/28 (you need to get cookies from the correct website matching your configured bridge mode, and you need to be able to use that website for the bridge to work)

aaaaa.. ok! yea I need to use messenger.com and not facebook.com (and for sure not using the LOGOUT button there)! sorry but I missed that totally.. it works now. thx again for your great work!
